language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install termcolor
  - pip install .
script:
  - cd rss_reader
  - nosetests --cover-branches --with-coverage --cover-min-percentage=50 --cover-package=rss_reader
  - pycodestyle --max-line-length=120 .
  - python ./../rss_reader_checker.py
<<<<<<< HEAD
  - cd -
=======
  - cd -

>>>>>>> 643f03232677a04e50332d838b1744c6efa37982
